export const FETCHED_USER_POSTS_SUCCESS = 'FETCHED_USER_POSTS_SUCCESS'; 
export const FETCHED_USER_POSTS_FAILED = 'FETCHED_USER_POSTS_FAILED'; 
export const STARTED_FETCHING_POSTS = 'STARTED_FETCHING_POSTS';
export const USER_NOT_POSTED_ANYTHING = 'USER_NOT_POSTED_ANYTHING';